### ISSUE TITLE
Team Filtering not working correctly

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/lapis-wiki#32] opened 2019-06-25 11:06 UTC
Team filtering on:

https://staging-lua.threefold.io/team

only filters on contribution level.
but filtering should be done (as agreed upon earlier):

Project + Contribution level.

Now we have duplicates 
<img width="1970" alt="Screenshot 2019-06-25 at 13 05 27" src="https://user-images.githubusercontent.com/29431263/60093547-fe844980-9749-11e9-9059-079b78e9fcdf.png">
<img width="1970" alt="Screenshot 2019-06-25 at 13 05 35" src="https://user-images.githubusercontent.com/29431263/60093548-ff1ce000-9749-11e9-827d-66c30356b592.png">
<img width="1970" alt="Screenshot 2019-06-25 at 13 05 46" src="https://user-images.githubusercontent.com/29431263/60093550-ff1ce000-9749-11e9-8e8e-7baa0facd7bb.png">
<img width="1970" alt="Screenshot 2019-06-25 at 13 05 52" src="https://user-images.githubusercontent.com/29431263/60093553-ff1ce000-9749-11e9-8ce6-214bcdde3ba8.png">

**Comment by VonSub** [comment] 2019-06-25 11:08
This webpage for instance should only show people that have project_id = 1

(see https://github.com/threefoldfoundation/data_team )

**Comment by abom** [comment] 2019-06-25 11:10
Please provide the macro in each of the examples you mentioned (what is the input of the team macro), not only the expected output.

**Comment by VonSub** [comment] 2019-06-25 11:59
@samaradel can you asnwer this?

**Comment by samaradel** [comment] 2019-06-25 12:06
For Founders sec
````
```
!!!team
link = "https://github.com/threefoldfoundation/data_team/tree/master/team"
order = "rank"
projects = [1]
contribution_types = [1]
```
````

For dev sec
````
```
!!!team
link = "https://github.com/threefoldfoundation/data_team/tree/master/team"
order = "random"
projects = [2,8]
contribution_types = [3,3]
```
````

For Ambassadors sec
````
```
!!!team
link = "https://github.com/threefoldfoundation/data_team/tree/master/team"
order = "rank"
contribution_types = [2]
```
````

**Comment by abom** [comment] 2019-06-25 12:59
Well the problem is in the data itself.

The first example, **[Sam](https://github.com/threefoldfoundation/data_team/blob/master/team/sam_taggart/publicinfo.toml)**, is a contributor of threefoldtech, and you filter by:
```

projects = [2,8]
contribution_types = [3,3]
```

The second example, **[Osman](https://github.com/threefoldfoundation/data_team/blob/master/team/osman_khan/publicinfo.toml)** is an ambassador and a founder in threefoldfoundation

and you filter by:

`contribution_types = [2]
`

**Comment by VonSub** [comment] 2019-06-25 13:10
For Ambassadors sec

```
!!!team
link = "https://github.com/threefoldfoundation/data_team/tree/master/team"
order = "rank"
contribution_types = [2]
```


Should also filter on project: 1

**Comment by abom** [comment] 2019-06-25 13:11
@samaradel Please see https://github.com/threefoldtech/OpenPublish/issues/32#issuecomment-505437445

**Comment by abom** [comment] 2019-06-25 13:32
Will be resolved by adding more contribution types to team data and filter by them (lots of work as members data need to be updated too).

**Closed as completed by abom** 2019-06-25 13:32 UTC
Labels: priority_major
